name: scancode
on:
  workflow_dispatch

jobs:
  scancode:
    name: ScanCode Python ${{ matrix.python_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python_version:
          # - '3.8'
          # - '3.9'
          # - '3.10'
          # - '3.11'
          - '3.12'
        os:
          - 'ubuntu-latest'
          # - 'windows-latest'
          # - 'macos-latest'
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        path: 'main'
    - name: Checkout ScanCode
      uses: actions/checkout@v4
      with:
        repository: 'nexB/scancode-toolkit'
        path: 'scancode-toolkit'
        ref: 'v32.2.1'
    - name: Use Python ${{ matrix.python_version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
    - name: Build and run ScanCode ${{ matrix.os }}
      if: ${{ ! startsWith(matrix.os, 'windows-') }}
      run: |
        cd scancode-toolkit
        ./configure
        source venv/bin/activate
        echo ${{ github.workspace }}/main
        extractcode --verbose ${{ github.workspace }}/main
        scancode -clpeui -n `python -c 'import multiprocessing; print(multiprocessing.cpu_count())'` --verbose --json-pp ${{ github.workspace }}/report.json --csv ${{ github.workspace }}/report.csv ${{ github.workspace }}/main
        scancode --from-json ${{ github.workspace }}/report.json --html-app ${{ github.workspace }}/report.html
    - name: Build and run ScanCode ${{ matrix.os }}
      if: ${{ startsWith(matrix.os, 'windows-') }}
      run: |
        cd scancode-toolkit
        configure
        venv\Scripts\activate
        echo ${{ github.workspace }}\main
        extractcode --verbose ${{ github.workspace }}\main
        scancode -clpeui -n $env:NUMBER_OF_PROCESSORS --verbose --json-pp ${{ github.workspace }}\report.json --csv ${{ github.workspace }}\report.csv ${{ github.workspace }}\main
        scancode --from-json ${{ github.workspace }}\report.json --html-app ${{ github.workspace }}\report.html
    - name: Store ScanCode Output
      uses: actions/upload-artifact@v4
      with:
        name: ScanCode Output
        path: |
          report.json
          report.csv
          report.html
          report_files/
        
                
